# Generated by Django 4.1.3 on 2022-12-22 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog_posts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="description",),
        migrations.AddField(
            model_name="task",
            name="author",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="task", name="content", field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name="task",
            name="date_posted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
