# Generated by Django 4.1.3 on 2023-01-14 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='phone',
        ),
    ]
