# Generated by Django 4.1.3 on 2023-01-14 08:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_feedback_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='commented_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
